---
- name: Ensure web server is installed and running
  hosts: webservers
  become: yes
  vars:
    http_port: 80
  tasks:
    - name: Install Apache HTTP server
      apt:
        name: apache2
        state: present
      notify: restart apache

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

